// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#pragma warning disable ASPIREDOCKERFILEBUILDER001

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Aspire.Hosting.Java;

/// <summary>
/// Generates the multi-stage Dockerfile that publishes a <see cref="JavaAppResource"/>.
/// </summary>
/// <remarks>
/// The container build is the only build: nothing here compiles the project on the host. The build stage
/// runs the project's own Maven or Gradle wrapper so the image is produced by exactly the tool version the
/// repository pins, and the runtime stage carries only a JRE and the resulting JAR.
/// </remarks>
internal static class JavaDockerfileGenerator
{
    // Kept outside /app so a build that writes into its own working directory cannot move the JAR
    // somewhere COPY --from does not look.
    private const string ContainerArtifactPath = "/build/app.jar";

    /// <summary>
    /// Where a build-produced OpenTelemetry agent lands in the runtime image. Fixed rather than mirroring
    /// the source layout so the entrypoint environment does not depend on the build tool's output paths.
    /// </summary>
    internal const string ContainerAgentPath = "/app/agent.jar";

    // Without this, target/ and build/ — routinely hundreds of megabytes after a local build — are
    // uploaded to the daemon and copied into the image by `COPY . .`. Multi-module projects put one next
    // to every module, hence the recursive patterns.
    // See https://docs.docker.com/build/concepts/context/#filename-and-location.
    private const string DefaultJavaBuildContextIgnoreContent = """
        # Generated by Aspire. Author <contextRoot>/.dockerignore to take over these rules.
        target
        **/target
        build
        **/build
        .gradle
        **/.gradle
        .git
        .gitignore
        .DS_Store
        .env
        .env.*
        .aspire
        aspire-output
        Dockerfile
        Dockerfile.*
        *.Dockerfile
        *.Dockerfile.dockerignore
        .dockerignore

        """;

    /// <summary>
    /// Determines which build tool the container image uses to produce the deployable JAR, and with which
    /// arguments.
    /// </summary>
    /// <remarks>
    /// Exposed separately from <see cref="Write"/> so the resolution rules — including the failure when no
    /// build tool can be found — can be exercised without running a publish pipeline.
    /// </remarks>
    /// <exception cref="DistributedApplicationException">No build tool is configured and none can be found on disk.</exception>
    internal static (JavaBuildTool Tool, string[] Args) ResolveBuildTool(JavaAppResource resource, string appDirectory)
        => JavaContainerBuild.ResolveToolAndArgs(resource, appDirectory);

    /// <summary>
    /// Resolves the full container build, including wrapper selection, without running a publish pipeline.
    /// </summary>
    /// <remarks>
    /// The publish pipeline reports a failure by throwing while reading a Dockerfile that was never
    /// written, which hides the message that explains what to fix, so the rejections are asserted here.
    /// </remarks>
    internal static void ResolveContainerBuildForTesting(JavaAppResource resource, string appDirectory)
        => JavaContainerBuild.Resolve(resource, appDirectory);

    public static void Write(JavaAppResource resource, string appDirectory, DockerfileBuilderCallbackContext context)
    {
        var logger = context.Services.GetService<ILogger<JavaAppResource>>();

        // An application added with a prebuilt JAR and no build configuration has nothing to build: the
        // artifact already exists in the context, so the image just carries it. Requiring a build tool here
        // would make a runnable application unpublishable.
        var prebuiltJar = TryGetPrebuiltJarPath(resource, appDirectory, out var jarPath) ? jarPath : null;

        // A <dockerfile>.dockerignore replaces the context root's .dockerignore rather than merging with
        // it, so an authored one wins outright.
        if (context.Resource.TryGetLastAnnotation<DockerfileBuildAnnotation>(out var dockerfileBuildAnnotation)
            && !File.Exists(Path.Combine(appDirectory, ".dockerignore")))
        {
            dockerfileBuildAnnotation.BuildContextIgnoreContent ??= BuildContextIgnoreContent(resource, prebuiltJar);
        }

        var build = prebuiltJar is null ? JavaContainerBuild.Resolve(resource, appDirectory) : null;
        var javaVersion = JavaVersionDetector.Detect(appDirectory);

        // The Java annotations live on the original JavaAppResource; ctx.Resource is the ContainerResource
        // PublishAsDockerFile substitutes in, and only carries the container-level annotations.
        context.Resource.TryGetLastAnnotation<DockerfileBaseImageAnnotation>(out var baseImageAnnotation);
        // A plain JDK image is always enough because a wrapper is required: the wrapper downloads the exact
        // tool version the project pins, so nothing has to come from the image. That also keeps the build
        // stage off the maven/gradle images, whose tags only exist for a subset of JDK releases and which
        // would otherwise pin a second, unrelated tool version.
        var buildImage = baseImageAnnotation?.BuildImage ?? $"docker.io/library/eclipse-temurin:{javaVersion}-jdk";
        var runtimeImage = baseImageAnnotation?.RuntimeImage ?? $"docker.io/library/eclipse-temurin:{javaVersion}-jre";

        if (build is not null)
        {
            WriteBuildStage(context, build, buildImage);
        }

        // Add intermediate FROM stages for any container files sources (e.g. FROM frontend AS frontend_stage).
        context.Builder.AddContainerFilesStages(context.Resource, logger);

        var runtimeStage = context.Builder.From(runtimeImage);

        // eclipse-temurin JRE images are Debian based, so the glibc user tools apply. An Alpine override
        // brings its own busybox tools, which take different switches.
        runtimeStage.Run(runtimeImage.Contains("alpine", StringComparison.OrdinalIgnoreCase)
            ? "addgroup -S app && adduser -S -G app app"
            : "groupadd --system --gid 999 app && useradd --system --gid 999 --uid 999 --no-create-home app");

        runtimeStage
            .WorkDir("/app")
            // Add COPY --from=<source> instructions for each container files source.
            .AddContainerFiles(context.Resource, "/app", logger);

        if (prebuiltJar is null)
        {
            runtimeStage.CopyFrom("build", ContainerArtifactPath, "/app/app.jar");
        }
        else
        {
            runtimeStage.Copy(prebuiltJar, "/app/app.jar");
        }

        // A relative agent path names a file the build produced, so it only exists in the build stage.
        // Carry it into the runtime image; the matching JAVA_TOOL_OPTIONS value is written by
        // WithOtelAgent, which points at ContainerAgentPath in publish mode.
        if (TryGetBuildProducedAgentPath(resource, out var agentPath))
        {
            if (prebuiltJar is null)
            {
                runtimeStage.CopyFrom("build", $"/app/{agentPath}", ContainerAgentPath);
            }
            else
            {
                // No build stage exists, so the agent has to already be in the context alongside the JAR.
                runtimeStage.Copy(agentPath, ContainerAgentPath);
            }
        }

        runtimeStage
            .User("app")
            // No shell form: with an ENTRYPOINT array the JVM is PID 1 and receives SIGTERM directly, so
            // Spring's shutdown hooks run instead of the container being killed after the stop timeout.
            .Entrypoint(["java", "-jar", "/app/app.jar"]);
    }

    private static void WriteBuildStage(DockerfileBuilderCallbackContext context, JavaContainerBuild build, string buildImage)
    {
        var buildStage = context.Builder
            .From(buildImage, "build")
            .WorkDir("/app");

        if (build.CacheHomeVariable is { } cacheHomeVariable)
        {
            // Pinned rather than inherited: the cache mount targets a fixed path, and the official tool
            // images point their cache elsewhere (the gradle image defaults GRADLE_USER_HOME to
            // /home/gradle/.gradle), which would leave the mount unused and re-download on every build.
            buildStage.Env(cacheHomeVariable, build.CacheTarget);
        }

        buildStage.Copy(".", ".");

        buildStage.RunWithMounts(
            // The artifact is staged outside /app so a build that writes into its own working directory
            // cannot move it somewhere COPY --from does not look.
            $"mkdir -p /build && {build.BuildCommand} && {build.SelectArtifactCommand}",
            // Both tools resolve dependencies from the network on a cold cache. A BuildKit cache mount
            // keeps the local repository across builds without baking it into a layer.
            // Locked because concurrent builds of sibling modules share one repository directory and
            // Maven's local repository is not safe for concurrent writers.
            // See https://maven.apache.org/guides/mini/guide-multiple-repositories.html
            $"type=cache,id={build.CacheId},target={build.CacheTarget},sharing=locked");
    }

    /// <summary>
    /// Gets the JAR to publish directly, for an application that runs a prebuilt JAR and configures no build.
    /// </summary>
    /// <remarks>
    /// A JAR path alone does not mean the artifact is prebuilt: it is also how a Maven or Gradle application
    /// names the JAR its own build produces, and those still have to be built in the image. This is therefore
    /// limited to the case where nothing at all describes a build — no build step, no launch tool, and no
    /// build file in the directory.
    /// </remarks>
    /// <exception cref="DistributedApplicationException">The JAR is outside the build context.</exception>
    internal static bool TryGetPrebuiltJarPath(JavaAppResource resource, string appDirectory, [NotNullWhen(true)] out string? jarPath)
    {
        jarPath = null;

        if (!resource.TryGetLastAnnotation<JavaJarPathAnnotation>(out var annotation)
            || resource.HasAnnotationOfType<JavaBuildStepAnnotation>()
            || resource.HasAnnotationOfType<JavaBuildToolAnnotation>()
            || HasBuildFile(appDirectory))
        {
            return false;
        }

        // Container paths are POSIX even when the AppHost authored a Windows-style relative path.
        var normalized = annotation.JarPath.Replace('\\', '/').TrimStart('.', '/');

        if (Path.IsPathRooted(annotation.JarPath)
            || normalized.Split('/').Contains(".."))
        {
            throw new DistributedApplicationException(
                $"Java application '{resource.Name}' cannot be published because its JAR " +
                $"'{annotation.JarPath}' is outside the build context '{appDirectory}'. Only files under " +
                "the application directory are uploaded to the container build.");
        }

        jarPath = normalized;

        return jarPath.Length > 0;
    }

    private static bool HasBuildFile(string appDirectory)
        => File.Exists(Path.Combine(appDirectory, "pom.xml"))
        || File.Exists(Path.Combine(appDirectory, "build.gradle"))
        || File.Exists(Path.Combine(appDirectory, "build.gradle.kts"))
        || File.Exists(Path.Combine(appDirectory, "settings.gradle"))
        || File.Exists(Path.Combine(appDirectory, "settings.gradle.kts"));

    /// <summary>
    /// The default <c>.dockerignore</c> content, with exceptions for files the image needs from the context.
    /// </summary>
    /// <remarks>
    /// The defaults exclude <c>target</c> and <c>build</c> because they are routinely hundreds of megabytes
    /// of build output. A prebuilt JAR normally sits in exactly those directories, so publishing it needs an
    /// exception; without one the COPY fails with "file not found in build context" even though the file is
    /// plainly there. Exceptions have to follow the exclusion they re-include.
    /// See https://docs.docker.com/build/concepts/context/#dockerignore-files.
    /// </remarks>
    private static string BuildContextIgnoreContent(JavaAppResource resource, string? prebuiltJarPath)
    {
        if (prebuiltJarPath is null)
        {
            return DefaultJavaBuildContextIgnoreContent;
        }

        var exceptions = new List<string> { prebuiltJarPath };

        if (TryGetBuildProducedAgentPath(resource, out var agentPath))
        {
            exceptions.Add(agentPath);
        }

        // Each parent directory has to be re-included too: Docker does not descend into a directory it has
        // already excluded, so "!target/app.jar" alone never matches when "target" itself is excluded.
        var reincluded = exceptions
            .SelectMany(ParentPathsAndSelf)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .Select(path => $"!{path}");

        return DefaultJavaBuildContextIgnoreContent + string.Join('\n', reincluded) + "\n";
    }

    private static IEnumerable<string> ParentPathsAndSelf(string path)
    {
        var segments = path.Split('/');

        for (var i = 1; i <= segments.Length; i++)
        {
            yield return string.Join('/', segments.Take(i));
        }
    }

    /// <summary>
    /// Gets the OpenTelemetry agent path when it names a file the build produces inside the context.
    /// </summary>
    /// <remarks>
    /// An absolute path is left alone. It cannot have come out of the build context, so it has to be
    /// supplied by the base image or a mount, and rewriting it would break that arrangement.
    /// </remarks>
    internal static bool TryGetBuildProducedAgentPath(JavaAppResource resource, [NotNullWhen(true)] out string? agentPath)
    {
        agentPath = null;

        if (!resource.TryGetLastAnnotation<JavaOtelAgentAnnotation>(out var annotation))
        {
            return false;
        }

        var authored = annotation.AgentPath;

        if (Path.IsPathRooted(authored))
        {
            return false;
        }

        // Container paths are POSIX even when the AppHost authored a Windows-style relative path.
        var normalized = authored.Replace('\\', '/');

        // Strip a single leading "./" only. Trimming the '.' and '/' characters as a set would turn
        // "../agents/otel.jar" into "agents/otel.jar" and emit a COPY for a path that was never in the
        // build context, failing the container build with a path the author never wrote.
        if (normalized.StartsWith("./", StringComparison.Ordinal))
        {
            normalized = normalized[2..];
        }

        // The Docker build context is the application directory, so a path that walks above it cannot be
        // copied forward no matter how it is spelled. Say so instead of silently rewriting it.
        if (normalized.Split('/').Any(segment => segment == ".."))
        {
            throw new DistributedApplicationException(
                $"The OpenTelemetry agent path '{annotation.AgentPath}' configured on resource '{resource.Name}' " +
                $"points outside the application directory, which is the Docker build context, so it cannot be " +
                $"published. Use a path inside '{resource.WorkingDirectory}', or an absolute path that the base " +
                $"image or a mount provides at runtime.");
        }

        agentPath = normalized;

        return agentPath.Length > 0;
    }

    /// <summary>
    /// The build-tool-specific pieces of the container build.
    /// </summary>
    /// <param name="Tool">The build tool that produces the JAR.</param>
    /// <param name="BuildCommand">The shell command that runs the build.</param>
    /// <param name="SelectArtifactCommand">The shell command that copies the produced JAR to a fixed path.</param>
    /// <param name="CacheTarget">The container path holding the tool's dependency cache.</param>
    /// <param name="CacheHomeVariable">The environment variable that pins the tool's cache to <paramref name="CacheTarget"/>, if it has one.</param>
    /// <param name="CacheId">The BuildKit cache identity, scoped per tool and resource.</param>
    private sealed record JavaContainerBuild(
        JavaBuildTool Tool,
        string BuildCommand,
        string SelectArtifactCommand,
        string CacheTarget,
        string? CacheHomeVariable,
        string CacheId)
    {

        public static JavaContainerBuild Resolve(JavaAppResource resource, string appDirectory)
        {
            var (tool, buildArgs) = ResolveToolAndArgs(resource, appDirectory);
            var wrapper = ResolveWrapperForContext(resource, appDirectory, tool);

            // A wrapper checked out from a Windows clone can arrive without the executable bit, and Git
            // does not record one on Windows at all. Invoking the interpreter directly sidesteps that
            // rather than failing with "permission denied" deep inside the container build.
            var invocation = $"sh ./{wrapper}";

            // Every argument is quoted because these values reach a container build as a shell command.
            // A version pinned with -Dspring.profiles.active='a b' or any value containing $ or ; would
            // otherwise be re-split or expanded by the shell, so the image would build differently from
            // the identical arguments used on the host, where they are passed as separate argv entries.
            var buildCommand = $"{invocation} {string.Join(' ', buildArgs.Select(ShellQuoteIfNeeded))}";

            var (outputGlob, cacheTarget, cacheHomeVariable) = tool switch
            {
                // Maven resolves its local repository from the home directory and offers no variable that
                // relocates it, so the mount targets root's default and the build stage runs as root.
                JavaBuildTool.Maven => ("target/*.jar", "/root/.m2", null),
                JavaBuildTool.Gradle => ("build/libs/*.jar", "/root/.gradle", "GRADLE_USER_HOME"),
                _ => throw new UnreachableException()
            };

            var selectArtifact = resource.TryGetLastAnnotation<JavaJarArtifactAnnotation>(out var artifact)
                ? $"cp {ShellQuote(artifact.RelativePath.Replace('\\', '/'))} {ContainerArtifactPath}"
                : SelectSingleJarCommand(outputGlob, resource.Name);

            return new JavaContainerBuild(
                tool,
                buildCommand,
                selectArtifact,
                cacheTarget,
                cacheHomeVariable,
                // Scoped per resource so two Java applications built concurrently do not contend on one
                // locked mount, and per tool because the two caches have different layouts.
                CacheId: $"aspire-java-{tool.ToString().ToLowerInvariant()}-{resource.Name.ToLowerInvariant()}");
        }

        /// <summary>
        /// Resolves the wrapper script as a path relative to the build context.
        /// </summary>
        /// <remarks>
        /// A wrapper is required rather than falling back to a <c>mvn</c>/<c>gradle</c> installed in the
        /// build image: the wrapper pins the tool version in the repository, so the container image is
        /// produced by the same version that built the project locally and in CI.
        /// <para>
        /// The wrapper also has to sit inside the build context, because only files under the context are
        /// uploaded to the daemon and reachable by <c>COPY . .</c>. A wrapper outside it exists on the host
        /// and not in the image, so the build would fail partway through with an opaque "not found".
        /// </para>
        /// </remarks>
        /// <exception cref="DistributedApplicationException">No wrapper is present, or the configured wrapper is outside the build context.</exception>
        private static string ResolveWrapperForContext(JavaAppResource resource, string appDirectory, JavaBuildTool tool)
        {
            var defaultWrapperName = tool switch
            {
                JavaBuildTool.Maven => "mvnw",
                JavaBuildTool.Gradle => "gradlew",
                _ => throw new UnreachableException()
            };

            if (resource.TryGetLastAnnotation<WrapperAnnotation>(out var configured))
            {
                // WithWrapperPath stores an absolute path, so this is what decides whether the file is
                // inside the context that was uploaded.
                var relative = Path.GetRelativePath(appDirectory, configured.WrapperPath).Replace('\\', '/');

                if (relative.StartsWith("../", StringComparison.Ordinal) || Path.IsPathRooted(relative))
                {
                    throw new DistributedApplicationException(
                        $"Java application '{resource.Name}' cannot be published because its wrapper " +
                        $"'{configured.WrapperPath}' is outside the build context '{appDirectory}'. " +
                        "Move the wrapper into the application directory, or set the build context to a " +
                        "directory that contains both.");
                }

                if (!File.Exists(configured.WrapperPath))
                {
                    throw new DistributedApplicationException(
                        $"Java application '{resource.Name}' cannot be published because the wrapper " +
                        $"configured with WithWrapperPath was not found at '{configured.WrapperPath}'.");
                }

                return relative;
            }

            if (!File.Exists(Path.Combine(appDirectory, defaultWrapperName)))
            {
                throw new DistributedApplicationException(
                    $"Java application '{resource.Name}' cannot be published because there is no " +
                    $"{defaultWrapperName} in '{appDirectory}'. Aspire builds the image with the project's " +
                    $"own wrapper so the container uses the tool version the repository pins. Generate one " +
                    $"with {JavaHostingExtensions.GenerateWrapperCommand(tool)}, or point at an existing " +
                    "wrapper with WithWrapperPath.");
            }

            return defaultWrapperName;
        }

        internal static (JavaBuildTool Tool, string[] Args) ResolveToolAndArgs(JavaAppResource resource, string appDirectory)
        {
            // A build step configured with WithMavenBuild/WithGradleBuild states both the tool and the
            // arguments that produce a deployable artifact, so it is the most precise source.
            if (resource.TryGetLastAnnotation<JavaBuildStepAnnotation>(out var buildStep))
            {
                return (buildStep.Tool, buildStep.Args);
            }

            // A launch goal such as spring-boot:run or bootRun identifies the tool but never packages, so
            // only the tool is taken from it and the packaging arguments are defaulted.
            if (resource.TryGetLastAnnotation<JavaBuildToolAnnotation>(out var buildTool))
            {
                return (buildTool.Tool, DefaultPackageArgs(buildTool.Tool));
            }

            // Left for an application added with a prebuilt JAR path and no build configuration: the
            // container still has to produce that JAR, so the tool comes from what is on disk.
            if (File.Exists(Path.Combine(appDirectory, "pom.xml")))
            {
                return (JavaBuildTool.Maven, DefaultPackageArgs(JavaBuildTool.Maven));
            }

            if (File.Exists(Path.Combine(appDirectory, "build.gradle"))
                || File.Exists(Path.Combine(appDirectory, "build.gradle.kts"))
                || File.Exists(Path.Combine(appDirectory, "settings.gradle"))
                || File.Exists(Path.Combine(appDirectory, "settings.gradle.kts")))
            {
                return (JavaBuildTool.Gradle, DefaultPackageArgs(JavaBuildTool.Gradle));
            }

            throw new DistributedApplicationException(
                $"The Java application '{resource.Name}' cannot be published because no build tool was found. " +
                $"Add a pom.xml or build.gradle to '{appDirectory}', or call WithMavenBuild or WithGradleBuild " +
                "to state how the deployable JAR is produced.");
        }

        private static string[] DefaultPackageArgs(JavaBuildTool tool) => tool switch
        {
            // -B disables the ANSI progress output that renders as noise in a build log, and -ntp drops
            // the per-artifact download lines. Tests are skipped because the container build produces a
            // deployable artifact; running the test suite belongs to CI, not to `aspire publish`.
            JavaBuildTool.Maven => ["-B", "-ntp", "-DskipTests", "package"],
            // The Gradle daemon outlives the RUN instruction's shell and would be killed with the layer,
            // so it only adds startup cost inside a container build.
            JavaBuildTool.Gradle => ["--no-daemon", "-x", "test", "build"],
            _ => throw new UnreachableException()
        };

        /// <summary>
        /// Emits a shell command that resolves <paramref name="outputGlob"/> to exactly one JAR and copies
        /// it to a fixed path.
        /// </summary>
        /// <remarks>
        /// The artifact name is only known after the build, and both tools emit more than one JAR in the
        /// common case: the Spring Boot plugin writes the executable <c>app-0.0.1-SNAPSHOT.jar</c> next to
        /// the base plugin's <c>app-0.0.1-SNAPSHOT-plain.jar</c>, and <c>-sources</c>/<c>-javadoc</c>
        /// artifacts appear as soon as those plugins are enabled. Those suffixes are filtered out, and
        /// anything still ambiguous fails the build with an actionable message rather than picking one
        /// arbitrarily and producing an image that starts and immediately exits with "no main manifest
        /// attribute".
        /// </remarks>
        private static string SelectSingleJarCommand(string outputGlob, string resourceName)
        {
            // Written as a single line because each Dockerfile RUN is one shell invocation. `ls` output is
            // safe to iterate here: Maven and Gradle artifact names come from the artifact id and version,
            // neither of which may contain whitespace.
            return string.Join(" && ",
                $"jars=$(ls {outputGlob} 2>/dev/null | grep -Ev '(-plain|-sources|-javadoc)\\.jar$' || true)",
                "count=$(printf '%s\\n' \"$jars\" | grep -c . || true)",
                $"if [ \"$count\" != \"1\" ]; then echo \"Aspire: expected exactly one application JAR from the build of '{resourceName}' matching {outputGlob}, found $count:\" >&2; echo \"$jars\" >&2; echo \"Use WithJarArtifact(\\\"<relative path>\\\") to select one.\" >&2; exit 1; fi",
                $"cp $jars {ContainerArtifactPath}");
        }

        private static string ShellQuote(string value) => $"'{value.Replace("'", "'\\''")}'";

        /// <summary>
        /// Quotes a build argument only when the shell would otherwise change its meaning.
        /// </summary>
        /// <remarks>
        /// These values reach the container build as a shell command, so a value containing whitespace,
        /// quotes, <c>$</c>, or <c>;</c> would be re-split or expanded and the image would build differently
        /// from the identical arguments used on the host, where they are passed as separate argv entries.
        /// Ordinary arguments such as <c>-DskipTests</c> are left bare so the generated Dockerfile stays
        /// readable.
        /// </remarks>
        private static string ShellQuoteIfNeeded(string value)
            => value.Length > 0 && value.All(static c => char.IsAsciiLetterOrDigit(c) || c is '.' or '_' or '/' or ':' or '=' or '+' or '@' or '-' or ',')
                ? value
                : ShellQuote(value);
    }
}

#pragma warning restore ASPIREDOCKERFILEBUILDER001
