// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Aspire.TypeSystem;
using Microsoft.Extensions.Logging;

namespace Aspire.Cli.Projects;

/// <summary>
/// The build tool that owns a Java AppHost project.
/// </summary>
internal enum JavaAppHostToolchain
{
    /// <summary>
    /// No build tool. The AppHost is a single file compiled directly with <c>javac</c>.
    /// </summary>
    Javac,

    /// <summary>
    /// A Maven project, identified by <c>pom.xml</c>.
    /// </summary>
    Maven,

    /// <summary>
    /// A Gradle project, identified by <c>build.gradle</c> or <c>build.gradle.kts</c>.
    /// </summary>
    Gradle
}

/// <summary>
/// Selects the build tool for a Java AppHost from the files on disk and rewrites the runtime spec to
/// match, mirroring what <see cref="TypeScriptAppHostToolchainResolver"/> does for package managers.
/// </summary>
/// <remarks>
/// <para>
/// Java AppHosts started life as a single <c>AppHost.java</c> compiled with <c>javac</c>, which needs
/// nothing but a JDK. That remains the default and the fallback: adopting a build tool is opt-in, and
/// is done by adding a <c>pom.xml</c> or <c>build.gradle</c>. A project model is what unlocks
/// third-party dependencies and full IDE support, because the Java language server derives its
/// classpath from build files.
/// </para>
/// <para>
/// Under a build tool the AppHost is still launched with a plain <c>java</c> command rather than
/// through <c>mvn exec:java</c> or <c>gradle run</c>. Those run the application inside, or as a child
/// of, the build tool's own JVM, so console signals reach the build tool instead of the AppHost and an
/// orderly shutdown never happens. Launching directly also means the arguments the CLI appends arrive
/// as real argv entries instead of being spliced into a shell string.
/// </para>
/// </remarks>
internal static class JavaAppHostToolchainResolver
{
    private const string MavenPomFileName = "pom.xml";
    private const string GradleBuildFileName = "build.gradle";
    private const string GradleKotlinBuildFileName = "build.gradle.kts";

    /// <summary>
    /// Directory the resolved runtime dependencies are copied into, relative to the build output.
    /// A directory of JARs is used rather than a classpath string because the JVM expands a
    /// <c>dir/*</c> classpath entry itself, so no shell and no generated argument file is needed.
    /// </summary>
    private const string DependencyDirectoryName = "aspire-deps";

    /// <summary>
    /// Gradle init script that adds a dependency-copying task to whatever project is being built.
    /// </summary>
    /// <remarks>
    /// An init script is used so a Gradle AppHost needs no cooperation from the user's build file.
    /// Maven ships <c>dependency:copy-dependencies</c> out of the box, but Gradle has no built-in
    /// equivalent, and requiring an edit to <c>build.gradle</c> would make adopting Gradle a worse
    /// experience than Maven for no reason.
    /// See https://docs.gradle.org/current/userguide/init_scripts.html.
    /// </remarks>
    private const string GradleInitScript = $$"""
        // Generated by Aspire. Adds the task that stages the AppHost's runtime classpath so the
        // AppHost can be launched with a plain `java` command instead of through Gradle.
        allprojects {
            tasks.register("aspireCopyDependencies", Copy) {
                from configurations.named("runtimeClasspath")
                into layout.buildDirectory.dir("{{DependencyDirectoryName}}")
            }
        }
        """;

    internal const string GradleInitScriptRelativePath = ".aspire/aspire-gradle-init.gradle";

    public static bool IsJavaLanguage(LanguageInfo? language)
    {
        return language is not null &&
            language.LanguageId.Value.Equals(KnownLanguageId.Java, StringComparison.OrdinalIgnoreCase);
    }

    public static JavaAppHostToolchain Resolve(DirectoryInfo appHostDirectory, ILogger? logger = null)
    {
        var resolution = ResolveWithReason(appHostDirectory);
        logger?.LogDebug(
            "Selected Java AppHost build tool '{BuildTool}' because {Reason}.",
            resolution.Toolchain,
            resolution.Reason);

        return resolution.Toolchain;
    }

    internal static JavaAppHostToolchainResolution ResolveWithReason(DirectoryInfo appHostDirectory)
    {
        // Only the AppHost directory is inspected. Unlike a Node package, a Java AppHost is not part
        // of a parent workspace graph, and a pom.xml in an ancestor directory usually belongs to an
        // unrelated project that happens to contain the AppHost folder.
        if (File.Exists(Path.Combine(appHostDirectory.FullName, MavenPomFileName)))
        {
            return new(JavaAppHostToolchain.Maven, $"{MavenPomFileName} found in {appHostDirectory.FullName}");
        }

        foreach (var gradleBuildFileName in new[] { GradleBuildFileName, GradleKotlinBuildFileName })
        {
            if (File.Exists(Path.Combine(appHostDirectory.FullName, gradleBuildFileName)))
            {
                return new(JavaAppHostToolchain.Gradle, $"{gradleBuildFileName} found in {appHostDirectory.FullName}");
            }
        }

        return new(JavaAppHostToolchain.Javac, $"no build file found in {appHostDirectory.FullName}");
    }

    public static string[] GetRequiredCommands(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Javac => ["javac", "java"],
            JavaAppHostToolchain.Maven => ["mvn", "java"],
            JavaAppHostToolchain.Gradle => ["gradle", "java"],
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    public static string GetDisplayName(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Javac => "Java",
            JavaAppHostToolchain.Maven => "Java (Maven)",
            JavaAppHostToolchain.Gradle => "Java (Gradle)",
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    /// <summary>
    /// Returns the command the build tool should be invoked with, preferring a wrapper checked into
    /// the project so the AppHost builds with the version the project pins.
    /// </summary>
    internal static string GetToolCommand(DirectoryInfo appHostDirectory, JavaAppHostToolchain toolchain)
    {
        var (wrapperName, fallbackCommand) = toolchain switch
        {
            JavaAppHostToolchain.Maven => (OperatingSystem.IsWindows() ? "mvnw.cmd" : "mvnw", "mvn"),
            JavaAppHostToolchain.Gradle => (OperatingSystem.IsWindows() ? "gradlew.bat" : "gradlew", "gradle"),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };

        var wrapperPath = Path.Combine(appHostDirectory.FullName, wrapperName);

        // A wrapper is referenced by absolute path because the process is started without a shell, so
        // a bare "mvnw" would be looked up on PATH and never found in the project directory.
        return File.Exists(wrapperPath) ? wrapperPath : fallbackCommand;
    }

    /// <summary>
    /// Rewrites the runtime spec for the resolved build tool. The <see cref="JavaAppHostToolchain.Javac"/>
    /// spec is returned unchanged so an AppHost without build files behaves exactly as before.
    /// </summary>
    public static RuntimeSpec ApplyToRuntimeSpec(RuntimeSpec baseRuntimeSpec, JavaAppHostToolchain toolchain, DirectoryInfo appHostDirectory)
    {
        if (toolchain == JavaAppHostToolchain.Javac)
        {
            return baseRuntimeSpec;
        }

        var toolCommand = GetToolCommand(appHostDirectory, toolchain);
        var classesDirectory = GetClassesDirectory(toolchain);
        var dependencyDirectory = GetDependencyDirectory(toolchain);

        return new RuntimeSpec
        {
            Language = baseRuntimeSpec.Language,
            DisplayName = GetDisplayName(toolchain),
            CodeGenLanguage = baseRuntimeSpec.CodeGenLanguage,
            DetectionPatterns = baseRuntimeSpec.DetectionPatterns,
            Initialize = baseRuntimeSpec.Initialize,
            InstallDependencies = CreateInstallCommand(toolchain, toolCommand),
            PreExecute = [CreateCompileCommand(toolchain, toolCommand)],
            Execute = CreateExecuteCommand(classesDirectory, dependencyDirectory),
            WatchExecute = baseRuntimeSpec.WatchExecute,
            PublishExecute = baseRuntimeSpec.PublishExecute,
            ExtensionLaunchCapability = baseRuntimeSpec.ExtensionLaunchCapability,
            CertificateBundleEnvironmentVariable = baseRuntimeSpec.CertificateBundleEnvironmentVariable,
            MigrationFiles = baseRuntimeSpec.MigrationFiles
        };
    }

    /// <summary>
    /// Writes the Gradle init script when the resolved toolchain needs it.
    /// </summary>
    /// <remarks>
    /// This is not done through <see cref="RuntimeSpec.MigrationFiles"/> because those are written
    /// with a plain file write that fails when the parent directory does not exist yet, and the
    /// script lives under <c>.aspire</c>.
    /// </remarks>
    public static async Task EnsureToolchainFilesExistAsync(
        DirectoryInfo appHostDirectory,
        JavaAppHostToolchain toolchain,
        CancellationToken cancellationToken)
    {
        if (toolchain != JavaAppHostToolchain.Gradle)
        {
            return;
        }

        var scriptPath = Path.Combine(
            appHostDirectory.FullName,
            GradleInitScriptRelativePath.Replace('/', Path.DirectorySeparatorChar));

        Directory.CreateDirectory(Path.GetDirectoryName(scriptPath)!);

        // Rewritten every run rather than only when missing, so a script left behind by an older
        // Aspire version cannot silently keep staging dependencies the wrong way.
        await File.WriteAllTextAsync(scriptPath, GradleInitScript, cancellationToken);
    }

    private static string GetClassesDirectory(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            // Both are the build tool's conventional output for main classes.
            // https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
            // https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout
            JavaAppHostToolchain.Maven => Path.Combine("target", "classes"),
            JavaAppHostToolchain.Gradle => Path.Combine("build", "classes", "java", "main"),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static string GetDependencyDirectory(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Maven => Path.Combine("target", DependencyDirectoryName),
            JavaAppHostToolchain.Gradle => Path.Combine("build", DependencyDirectoryName),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static CommandSpec CreateInstallCommand(JavaAppHostToolchain toolchain, string toolCommand)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Maven => new CommandSpec
            {
                Command = toolCommand,
                // Batch mode keeps the transfer progress spinner out of the CLI's captured output.
                // Only runtime-scoped dependencies are staged: test and provided dependencies are not
                // on the application's runtime classpath and staging them can shadow real versions.
                Args =
                [
                    "-B", "-q",
                    "dependency:copy-dependencies",
                    $"-DoutputDirectory={GetDependencyDirectory(toolchain)}",
                    "-DincludeScope=runtime"
                ]
            },
            JavaAppHostToolchain.Gradle => new CommandSpec
            {
                Command = toolCommand,
                Args = ["-q", "--init-script", GradleInitScriptRelativePath, "aspireCopyDependencies"]
            },
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static CommandSpec CreateCompileCommand(JavaAppHostToolchain toolchain, string toolCommand)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Maven => new CommandSpec
            {
                Command = toolCommand,
                Args = ["-B", "-q", "compile"]
            },
            JavaAppHostToolchain.Gradle => new CommandSpec
            {
                Command = toolCommand,
                Args = ["-q", "classes"]
            },
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static CommandSpec CreateExecuteCommand(string classesDirectory, string dependencyDirectory)
    {
        // "dir/*" is expanded by the JVM into every JAR in that directory. It is not a shell glob, so
        // it works with no shell involved and stays correct when the directory is empty.
        // https://docs.oracle.com/en/java/javase/25/docs/specs/man/java.html#standard-options-for-java
        var classPath = string.Join(Path.PathSeparator, [classesDirectory, Path.Combine(dependencyDirectory, "*")]);

        return new CommandSpec
        {
            Command = "java",
            // {args} is deliberately absent. When no argument contains that placeholder the CLI
            // appends its arguments as separate argv entries, whereas substituting the placeholder
            // joins them into one space-separated string that the AppHost then has to re-split.
            Args = ["-cp", classPath, "AppHost"]
        };
    }
}

internal readonly record struct JavaAppHostToolchainResolution(JavaAppHostToolchain Toolchain, string Reason);
