// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Aspire.TypeSystem;
using Microsoft.Extensions.Logging;

namespace Aspire.Cli.Projects;

/// <summary>
/// The build tool that owns a Java AppHost project.
/// </summary>
internal enum JavaAppHostToolchain
{
    /// <summary>
    /// No build tool. The AppHost is a single file compiled directly with <c>javac</c>.
    /// </summary>
    Javac,

    /// <summary>
    /// A Maven project, identified by <c>pom.xml</c>.
    /// </summary>
    Maven,

    /// <summary>
    /// A Gradle project, identified by <c>build.gradle</c> or <c>build.gradle.kts</c>.
    /// </summary>
    Gradle
}

/// <summary>
/// Selects the build tool for a Java AppHost from the files on disk and rewrites the runtime spec to
/// match, mirroring what <see cref="TypeScriptAppHostToolchainResolver"/> does for package managers.
/// </summary>
/// <remarks>
/// <para>
/// Java AppHosts started life as a single <c>AppHost.java</c> compiled with <c>javac</c>, which needs
/// nothing but a JDK. That remains the default and the fallback: adopting a build tool is opt-in, and
/// is done by adding a <c>pom.xml</c> or <c>build.gradle</c>. A project model is what unlocks
/// third-party dependencies and full IDE support, because the Java language server derives its
/// classpath from build files.
/// </para>
/// <para>
/// Under a build tool the AppHost is still launched with a plain <c>java</c> command rather than
/// through <c>mvn exec:java</c> or <c>gradle run</c>. Those run the application inside, or as a child
/// of, the build tool's own JVM, so console signals reach the build tool instead of the AppHost and an
/// orderly shutdown never happens. Launching directly also means the arguments the CLI appends arrive
/// as real argv entries instead of being spliced into a shell string.
/// </para>
/// </remarks>
internal static class JavaAppHostToolchainResolver
{
    private const string MavenPomFileName = "pom.xml";
    private const string GradleBuildFileName = "build.gradle";
    private const string GradleKotlinBuildFileName = "build.gradle.kts";

    /// <summary>
    /// Directory the resolved runtime dependencies are copied into, relative to the build output.
    /// A directory of JARs is used rather than a classpath string because the JVM expands a
    /// <c>dir/*</c> classpath entry itself, so no shell and no generated argument file is needed.
    /// </summary>
    private const string DependencyDirectoryName = "aspire-deps";

    /// <summary>
    /// Gradle init script that adds a dependency-copying task to whatever project is being built.
    /// </summary>
    /// <remarks>
    /// An init script is used so a Gradle AppHost needs no cooperation from the user's build file.
    /// Maven ships <c>dependency:copy-dependencies</c> out of the box, but Gradle has no built-in
    /// equivalent, and requiring an edit to <c>build.gradle</c> would make adopting Gradle a worse
    /// experience than Maven for no reason.
    /// See https://docs.gradle.org/current/userguide/init_scripts.html.
    /// </remarks>
    private const string GradleInitScript = $$"""
        // Generated by Aspire. Adds the task that stages the AppHost's runtime classpath so the
        // AppHost can be launched with a plain `java` command instead of through Gradle.
        allprojects {
            tasks.register("aspireCopyDependencies", Copy) {
                from configurations.named("runtimeClasspath")
                into layout.buildDirectory.dir("{{DependencyDirectoryName}}")
            }
        }
        """;

    internal const string GradleInitScriptRelativePath = ".aspire/aspire-gradle-init.gradle";

    /// <summary>
    /// <see cref="GradleInitScriptRelativePath"/> with the separators this platform uses.
    /// </summary>
    private static string GradleInitScriptPath => GradleInitScriptRelativePath.Replace('/', Path.DirectorySeparatorChar);

    public static bool IsJavaLanguage(LanguageInfo? language)
    {
        return language is not null &&
            language.LanguageId.Value.Equals(KnownLanguageId.Java, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Conventional source root a build tool compiles from. When the AppHost lives here the build
    /// file is at the project root, three directories up.
    /// https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
    /// </summary>
    private static readonly string[] s_conventionalSourceRootSegments = ["src", "main", "java"];

    public static JavaAppHostToolchainResolution Resolve(DirectoryInfo appHostDirectory, ILogger? logger = null)
    {
        var resolution = ResolveWithReason(appHostDirectory);
        logger?.LogDebug(
            "Selected Java AppHost build tool '{BuildTool}' rooted at '{ProjectDirectory}' because {Reason}.",
            resolution.Toolchain,
            resolution.ProjectDirectory.FullName,
            resolution.Reason);

        return resolution;
    }

    internal static JavaAppHostToolchainResolution ResolveWithReason(DirectoryInfo appHostDirectory)
    {
        // The AppHost directory is checked first, then the project root implied by the conventional
        // source layout. An unbounded walk up the tree is deliberately avoided: a pom.xml in some
        // arbitrary ancestor usually belongs to an unrelated project that happens to contain the
        // AppHost folder, whereas src/main/java is only ever a build tool's source root.
        foreach (var candidate in GetCandidateProjectDirectories(appHostDirectory))
        {
            if (File.Exists(Path.Combine(candidate.FullName, MavenPomFileName)))
            {
                return new(JavaAppHostToolchain.Maven, candidate, $"{MavenPomFileName} found in {candidate.FullName}");
            }

            foreach (var gradleBuildFileName in new[] { GradleBuildFileName, GradleKotlinBuildFileName })
            {
                if (File.Exists(Path.Combine(candidate.FullName, gradleBuildFileName)))
                {
                    return new(JavaAppHostToolchain.Gradle, candidate, $"{gradleBuildFileName} found in {candidate.FullName}");
                }
            }
        }

        return new(JavaAppHostToolchain.Javac, appHostDirectory, $"no build file found in {appHostDirectory.FullName}");
    }

    private static IEnumerable<DirectoryInfo> GetCandidateProjectDirectories(DirectoryInfo appHostDirectory)
    {
        yield return appHostDirectory;

        // Walk back out of src/main/java only when the directory names actually match, so an AppHost
        // that merely sits three levels deep is not mistaken for a conventional project layout.
        var candidate = appHostDirectory;
        foreach (var segment in s_conventionalSourceRootSegments.Reverse())
        {
            if (!string.Equals(candidate.Name, segment, PathComparison) || candidate.Parent is null)
            {
                yield break;
            }

            candidate = candidate.Parent;
        }

        yield return candidate;
    }

    private static StringComparison PathComparison =>
        OperatingSystem.IsLinux() ? StringComparison.Ordinal : StringComparison.OrdinalIgnoreCase;

    public static string[] GetRequiredCommands(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            // javac is required for every toolchain: a Maven or Gradle AppHost resolves its dependencies
            // with the build tool but is still compiled with javac. See CreateCompileCommand.
            JavaAppHostToolchain.Javac => ["javac", "java"],
            JavaAppHostToolchain.Maven => ["mvn", "javac", "java"],
            JavaAppHostToolchain.Gradle => ["gradle", "javac", "java"],
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    public static string GetDisplayName(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Javac => "Java",
            JavaAppHostToolchain.Maven => "Java (Maven)",
            JavaAppHostToolchain.Gradle => "Java (Gradle)",
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    /// <summary>
    /// Returns how the build tool should be invoked. The wrapper checked into the project is required,
    /// so the AppHost always builds with the tool version the project pins.
    /// </summary>
    /// <param name="projectDirectory">Directory holding the build file and the wrapper.</param>
    /// <param name="appHostDirectory">Directory the command runs in, which the wrapper path is relative to.</param>
    /// <param name="toolchain">The resolved build tool.</param>
    internal static JavaToolInvocation GetToolInvocation(
        DirectoryInfo projectDirectory,
        DirectoryInfo appHostDirectory,
        JavaAppHostToolchain toolchain)
    {
        var (wrapperName, generateCommand) = toolchain switch
        {
            // -N keeps the goal from recursing into the modules of a multi-module build.
            JavaAppHostToolchain.Maven => (OperatingSystem.IsWindows() ? "mvnw.cmd" : "mvnw", "mvn -N wrapper:wrapper"),
            JavaAppHostToolchain.Gradle => (OperatingSystem.IsWindows() ? "gradlew.bat" : "gradlew", "gradle wrapper"),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };

        var wrapperPath = Path.Combine(projectDirectory.FullName, wrapperName);

        // A globally installed Maven or Gradle is deliberately not used as a fallback: the wrapper pins the
        // tool version in the repository, so every machine builds the AppHost with the same one. Falling
        // back silently would make the AppHost build depend on whatever the developer happens to have.
        if (!File.Exists(wrapperPath))
        {
            throw new InvalidOperationException(
                $"The Java AppHost project in '{projectDirectory.FullName}' declares a {GetDisplayName(toolchain)} " +
                $"build but ships no {wrapperName}. Generate one with '{generateCommand}', or remove the " +
                "build file to build the AppHost with javac instead.");
        }

        if (!OperatingSystem.IsWindows())
        {
            // Referenced by absolute path because the process is started without a shell, so a bare "mvnw"
            // would be looked up on PATH and never found in the project directory.
            return new JavaToolInvocation(wrapperPath, []);
        }

        // On Windows the wrappers are batch files. Launching one directly with redirected stdout can
        // silently produce no output (see NpmRunner, which hits the same problem with npm.cmd), so the
        // command interpreter runs it instead.
        //
        // cmd.exe strips quotes in ways that do not match how ProcessStartInfo.ArgumentList escapes
        // arguments: if the *first* token is quoted, cmd removes that quote and the last one on the
        // line, mangling everything in between. Passing the wrapper as a path relative to the working
        // directory keeps that token free of spaces, so ArgumentList never quotes it and the hazard
        // cannot arise. See the quote-processing rules printed by `cmd /?`.
        var relativeWrapperPath = Path.GetRelativePath(appHostDirectory.FullName, wrapperPath);

        return new JavaToolInvocation(
            Environment.GetEnvironmentVariable("ComSpec") ?? "cmd.exe",
            ["/c", relativeWrapperPath]);
    }

    /// <summary>
    /// Rewrites the runtime spec for the resolved build tool. The <see cref="JavaAppHostToolchain.Javac"/>
    /// spec is returned unchanged so an AppHost without build files behaves exactly as before.
    /// </summary>
    public static RuntimeSpec ApplyToRuntimeSpec(RuntimeSpec baseRuntimeSpec, JavaAppHostToolchainResolution resolution, DirectoryInfo appHostDirectory)
    {
        var toolchain = resolution.Toolchain;
        if (toolchain == JavaAppHostToolchain.Javac)
        {
            return baseRuntimeSpec;
        }

        var invocation = GetToolInvocation(resolution.ProjectDirectory, appHostDirectory, toolchain);

        // Commands run with the AppHost directory as their working directory, which is not the project
        // directory in the src/main/java layout, so every path below is rewritten relative to it.
        var projectPath = GetRelativeProjectPath(resolution.ProjectDirectory, appHostDirectory);
        var classesDirectory = CombineProjectPath(projectPath, GetClassesDirectory(toolchain));
        var dependencyDirectory = CombineProjectPath(projectPath, GetDependencyDirectory(toolchain));

        return new RuntimeSpec
        {
            Language = baseRuntimeSpec.Language,
            DisplayName = GetDisplayName(toolchain),
            CodeGenLanguage = baseRuntimeSpec.CodeGenLanguage,
            DetectionPatterns = baseRuntimeSpec.DetectionPatterns,
            Initialize = baseRuntimeSpec.Initialize,
            InstallDependencies = CreateInstallCommand(toolchain, invocation, projectPath),
            PreExecute = [CreateCompileCommand(baseRuntimeSpec, classesDirectory, dependencyDirectory)],
            Execute = CreateExecuteCommand(classesDirectory, dependencyDirectory),
            WatchExecute = baseRuntimeSpec.WatchExecute,
            PublishExecute = baseRuntimeSpec.PublishExecute,
            ExtensionLaunchCapability = baseRuntimeSpec.ExtensionLaunchCapability,
            CertificateBundleEnvironmentVariable = baseRuntimeSpec.CertificateBundleEnvironmentVariable,
            MigrationFiles = baseRuntimeSpec.MigrationFiles
        };
    }

    /// <summary>
    /// Writes the Gradle init script when the resolved toolchain needs it.
    /// </summary>
    /// <remarks>
    /// This is not done through <see cref="RuntimeSpec.MigrationFiles"/> because those are written
    /// with a plain file write that fails when the parent directory does not exist yet, and the
    /// script lives under <c>.aspire</c>.
    /// </remarks>
    public static async Task EnsureToolchainFilesExistAsync(
        JavaAppHostToolchainResolution resolution,
        CancellationToken cancellationToken)
    {
        if (resolution.Toolchain != JavaAppHostToolchain.Gradle)
        {
            return;
        }

        // Written into the project directory rather than the AppHost directory so it sits alongside
        // the build file it augments, which is where the --init-script argument points.
        var scriptPath = Path.Combine(resolution.ProjectDirectory.FullName, GradleInitScriptPath);

        Directory.CreateDirectory(Path.GetDirectoryName(scriptPath)!);

        // Rewritten every run rather than only when missing, so a script left behind by an older
        // Aspire version cannot silently keep staging dependencies the wrong way.
        await File.WriteAllTextAsync(scriptPath, GradleInitScript, cancellationToken);
    }

    /// <summary>
    /// Path from the AppHost directory to the project directory, or <see langword="null"/> when they are
    /// the same. Null rather than "." so the common flat layout keeps clean, unprefixed relative paths.
    /// </summary>
    private static string? GetRelativeProjectPath(DirectoryInfo projectDirectory, DirectoryInfo appHostDirectory)
    {
        var relativePath = Path.GetRelativePath(appHostDirectory.FullName, projectDirectory.FullName);

        return relativePath == "." ? null : relativePath;
    }

    private static string CombineProjectPath(string? projectPath, string path)
    {
        return projectPath is null ? path : Path.Combine(projectPath, path);
    }

    /// <summary>
    /// Arguments that point the build tool at a project other than its working directory. Both tools
    /// need this because the AppHost is launched from its own directory, not the project root.
    /// </summary>
    private static string[] GetProjectSelectionArgs(JavaAppHostToolchain toolchain, string? projectPath)
    {
        if (projectPath is null)
        {
            return [];
        }

        return toolchain switch
        {
            // https://maven.apache.org/ref/current/maven-embedder/cli.html
            JavaAppHostToolchain.Maven => ["-f", Path.Combine(projectPath, MavenPomFileName)],
            // https://docs.gradle.org/current/userguide/command_line_interface.html
            JavaAppHostToolchain.Gradle => ["-p", projectPath],
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static string GetClassesDirectory(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            // Both are the build tool's conventional output for main classes.
            // https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
            // https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout
            JavaAppHostToolchain.Maven => Path.Combine("target", "classes"),
            JavaAppHostToolchain.Gradle => Path.Combine("build", "classes", "java", "main"),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static string GetDependencyDirectory(JavaAppHostToolchain toolchain)
    {
        return toolchain switch
        {
            JavaAppHostToolchain.Maven => Path.Combine("target", DependencyDirectoryName),
            JavaAppHostToolchain.Gradle => Path.Combine("build", DependencyDirectoryName),
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };
    }

    private static CommandSpec CreateInstallCommand(
        JavaAppHostToolchain toolchain,
        JavaToolInvocation invocation,
        string? projectPath)
    {
        var toolArgs = toolchain switch
        {
            // Batch mode keeps the transfer progress spinner out of the CLI's captured output.
            // Only runtime-scoped dependencies are staged: test and provided dependencies are not
            // on the application's runtime classpath and staging them can shadow real versions.
            JavaAppHostToolchain.Maven => (string[])
            [
                "-B", "-q",
                .. GetProjectSelectionArgs(toolchain, projectPath),
                "dependency:copy-dependencies",
                // Maven resolves a relative outputDirectory against the project's base directory, so
                // the path is expressed relative to the project rather than the working directory.
                $"-DoutputDirectory={GetDependencyDirectory(toolchain)}",
                "-DincludeScope=runtime"
            ],
            JavaAppHostToolchain.Gradle =>
            [
                "-q",
                .. GetProjectSelectionArgs(toolchain, projectPath),
                "--init-script", CombineProjectPath(projectPath, GradleInitScriptPath),
                "aspireCopyDependencies"
            ],
            _ => throw new ArgumentOutOfRangeException(nameof(toolchain), toolchain, null)
        };

        return invocation.CreateCommand(toolArgs);
    }

    /// <summary>
    /// Compiles the AppHost with javac, against the dependency classpath the build tool staged.
    /// </summary>
    /// <remarks>
    /// The build tool resolves dependencies but does not compile, because neither Maven nor Gradle can
    /// be told from the command line about the generated SDK under <c>.aspire/modules</c>. Maven has no
    /// user property for an extra source root or compiler argument — <c>compilerArgs</c>,
    /// <c>compilerArgument</c>, and the source roots are all pom-only — so <c>mvnw compile</c> fails with
    /// "package aspire does not exist" no matter what is passed after the goal. Editing the user's
    /// <c>pom.xml</c> to add a source root is not an option either: the build file belongs to them.
    /// <para>
    /// Compiling with javac instead keeps the AppHost building the same way under all three toolchains,
    /// and the build tool keeps the two jobs it is actually needed for: resolving third-party
    /// dependencies, and giving the IDE a real project model.
    /// </para>
    /// <para>
    /// The consequence, which is worth knowing: compiler configuration in <c>pom.xml</c> or
    /// <c>build.gradle</c> — annotation processors such as Lombok, custom lint settings, an alternative
    /// compiler — does not apply to <c>AppHost.java</c>.
    /// </para>
    /// </remarks>
    private static CommandSpec CreateCompileCommand(RuntimeSpec baseRuntimeSpec, string classesDirectory, string dependencyDirectory)
    {
        var baseCompile = baseRuntimeSpec.PreExecute?.FirstOrDefault()
            ?? throw new InvalidOperationException("The Java runtime spec has no compile step to adapt for a build tool.");

        var baseArgs = baseCompile.Args ?? [];

        // "dir/*" is expanded by the JVM's own launcher rather than the shell, so it needs no shell and
        // stays correct when the directory is empty.
        // https://docs.oracle.com/en/java/javase/25/docs/specs/man/javac.html#standard-options
        string[] addedArgs =
        [
            "-classpath", Path.Combine(dependencyDirectory, "*"),
            // The AppHost directory is the working directory and is also the project's source root under
            // both supported layouts, so this is what lets the AppHost reference the project's own
            // classes. It has to be set explicitly because javac otherwise defaults the source path to
            // the class path, which -classpath has just replaced.
            "-sourcepath", ".",
            // Output goes to the build tool's own directory rather than the javac toolchain's
            // .java-build, so that `mvn clean` / `gradle clean` removes it and it is already ignored by
            // any Maven or Gradle .gitignore.
            "-d", classesDirectory
        ];

        // The javac options and the source arguments are reused from the base spec rather than repeated
        // here, so the two toolchains cannot drift apart. The output directory is the one thing replaced.
        var outputIndex = Array.IndexOf(baseArgs, "-d");

        var args = outputIndex >= 0 && outputIndex + 1 < baseArgs.Length
            ? (string[])[.. baseArgs[..outputIndex], .. addedArgs, .. baseArgs[(outputIndex + 2)..]]
            : [.. addedArgs, .. baseArgs];

        return new CommandSpec
        {
            Command = baseCompile.Command,
            Args = args
        };
    }

    private static CommandSpec CreateExecuteCommand(string classesDirectory, string dependencyDirectory)
    {
        // "dir/*" is expanded by the JVM into every JAR in that directory. It is not a shell glob, so
        // it works with no shell involved and stays correct when the directory is empty.
        // https://docs.oracle.com/en/java/javase/25/docs/specs/man/java.html#standard-options-for-java
        var classPath = string.Join(Path.PathSeparator, [classesDirectory, Path.Combine(dependencyDirectory, "*")]);

        return new CommandSpec
        {
            Command = "java",
            // {args} is deliberately absent. When no argument contains that placeholder the CLI
            // appends its arguments as separate argv entries, whereas substituting the placeholder
            // joins them into one space-separated string that the AppHost then has to re-split.
            Args = ["-cp", classPath, "AppHost"]
        };
    }
}

/// <summary>
/// How a build tool wrapper is launched: the executable, plus any arguments that must precede the
/// tool's own. Windows needs a command interpreter in front of the batch wrapper, other platforms
/// invoke it directly.
/// </summary>
internal readonly record struct JavaToolInvocation(string Command, string[] PrefixArgs)
{
    public CommandSpec CreateCommand(string[] args)
    {
        return new CommandSpec
        {
            Command = Command,
            Args = [.. PrefixArgs, .. args]
        };
    }
}

/// <summary>
/// The build tool selected for a Java AppHost, the directory its build file lives in, and why it was chosen.
/// </summary>
/// <remarks>
/// <see cref="ProjectDirectory"/> is not always the AppHost's own directory: with the conventional
/// <c>src/main/java/AppHost.java</c> layout the build file is at the project root. Commands are still
/// launched from the AppHost directory, so paths are made relative to it rather than to the project.
/// </remarks>
internal readonly record struct JavaAppHostToolchainResolution(
    JavaAppHostToolchain Toolchain,
    DirectoryInfo ProjectDirectory,
    string Reason);
